---
title: "Project Euler 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

```{Rcpp}
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
Rcpp::NumericVector PrimeFactors(double numb) {
  unsigned long long number = static_cast<unsigned long long>(numb);
  std::vector<unsigned long long> factors;
  Rprintf("%d %d %d\n", sizeof(unsigned long), sizeof(unsigned long long), sizeof(double));
  while (number%2==0) {
        number /= 2;
        factors.push_back(2);
  }
  
    unsigned long long divisor = 3ul;
   //  Rprintf("%lld\n", number);

    double maxprime = sqrt(number);
    while (divisor <= maxprime) {
        if (number%divisor == 0) {
            number = number/divisor;
            factors.push_back(divisor);
            maxprime = sqrt(number);
        } else {
            divisor += 2ul;
        }
    }
    factors.push_back(number);
    
    Rcpp::NumericVector a(factors.size());
    for (size_t i=0;i<factors.size();i++)
      a(i)=static_cast<double>(factors[i]);

    return a;
}

```


```{r}
system.time(a <- PrimeFactors(600851475143))
print(a)
```